remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: how the fuck do you use this
description: how the hell do you use this im so serious
